import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lifetime Fitness Center",
  description: "Generated by WellnessZ",
  icons: {
    icon: '/Lifetime App icon.png',
  },
  other: {
    "google-site-verification": "81rE9ZOF0lpX5WhV05QzvI8G5mgDGz7mKIs3vC_RuxI"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/Lifetime App icon.png" sizes="any" />
      <body className={inter.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
